### PR TITLE
Specification for GmodNET.VersionTool

### PR DESCRIPTION
**Pull request by GlebChili**
I've decided to develop a version build tool to manage versioning of GmodNET core and side projects. Here is a specification for such solution.

### CODE REVIEW

**Comment by GlebChili** [comment]
@AaronJThompson  @phaseflowcentral I've discovered an issue with my versioning proposal and NuGet clients: pre-release tag is too long (must not exceed 20 characters). The proposal will be modified now.

**Comment by GlebChili** [comment]
Never mind. The "20 characters" limitation was fixed in recent NuGet client and known servers. The real issue is the number of point-separated numbers. We should use one big number instead.

**Comment by GlebChili** [comment]
Specification updated.

**Comment by AaronJThompson** [comment]
I think the idea is great, but the resulting version numbers don't feel human readable. I think most developers would like have to have nice version numbers for full releases, especially when it comes to communicating changes to users. Could we do some Nuget interop to simplify the version numbers whilst still checking if the version number is available? Because ideally, we'd stick to the SemVer spec so that users and developers can use fuzzy versioning in their package references

**Comment by GlebChili** [comment]
@AaronJThompson But we will have nice version for release version. Build metadata (after the'+' sign) is skipped in NuGet. So If we have release version 1.0.0+head.master.commit.7777777 of GmodNET.VersionTool, then the corresponding NuGet package will be GmodNET.VersionTool.1.0.0.nupkg.  It is a part of NuGet specification: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#normalized-version-numbers.

But we will be able to access build information from within assembly for debug information (using [FileVersionInfo](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.fileversioninfo?view=netcore-3.1)).

**Comment by AaronJThompson** [comment]
Ah I wasn't aware.  Can I get some clarification on the exact purposes of the VersionTool as opposed to normal Nuget versioning?

**Comment by GlebChili** [comment]
@AaronJThompson I want to automatically deploy nightly builds to preview nuget feed from CI. So we need to generate unique preview version number on each commit. The feed will look like this one I've already made: https://dev.azure.com/GmodNET/gmodnet-artifacts/_packaging?_a=feed&feed=gmodnet-packages

**Comment by GlebChili** [comment]
We will deploy only non-preview versions to nuget.org

**Comment by GlebChili** [comment]
@AaronJThompson Here https://dev.azure.com/GmodNET/gmodnet-artifacts/_packaging?_a=package&feed=gmodnet-packages&package=GmodNET.VersionTool&protocolType=NuGet&version=0.2.0-alpha.1.21500529.dev&view=versions

Versions post 0.2.0-alpha.0 are versioned by GmodNET.VersionTool itself. That's what it will look like in NuGet feeds. Remember that this versions are pre-release, stable versions will look just like `1.0.0`.

**Review by AaronJThompson — APPROVED** [review]
Approved, great work! Thanks for the clarification

**Pull request merged**
